cabal-version:       3.12
name:                telomare
version:             0.1.0.0
synopsis:            A simple but robust virtual machine
description:         Please see README.md
homepage:            https://github.com/Stand-In-Language/stand-in-language#readme
license:             Apache-2.0
license-file:        LICENSE
author:              Sam Griffin
maintainer:          sam.griffin@gmail.com
copyright:           2026 Sam Griffin
category:            Language
build-type:          Simple
-- The nix build compiles from `cabal sdist` output, so anything the test
-- suites open at run time has to be listed here or it simply will not be
-- there. That is the whole reason the Telomare programs appear below.
extra-source-files:  CHANGELOG.md
                     README.md
                     *.tel
                     test/programs/**/*.tel

library
  hs-source-dirs:      src
  exposed-modules:     Telomare.Artifact
                     , Telomare.Certificate
                     , Telomare.Desugar
                     , Telomare.EAL
                     , Telomare.IC
                     , Telomare.Error
                     , Telomare.Driver
                     , Telomare.Eval.Reference
                     , Telomare.Fast
                     , Telomare.IR.Base
                     , Telomare.IR.Builder
                     , Telomare.IR.Core
                     , Telomare.IR.Loc
                     , Telomare.IR.Surface
                     , Telomare.IR.Types
                     , Telomare.Levels
                     , Telomare.Lexical
                     , Telomare.Machine
                     , Telomare.Eval.Meter
                     , Telomare.Expand
                     , Telomare.Parse
                     , Telomare.PrettyPrint
                     , Telomare.PrettyPrint.Indent
                     , Telomare.Resolve
                     , Telomare.Size
                     , Telomare.Size.IR
                     , Telomare.TypeCheck
                     , Telomare.Util
  build-depends:       base
                     , binary
                     , bytestring
                     , containers
                     , data-fix
                     , deepseq
                     , dlist
                     , filepath
                     , megaparsec
                     , memory
                     , mtl
                     , recursion-schemes
                     , transformers
                     , lens
                     , cryptonite
                     , utf8-string
                     , validity
                     , genvalidity
                     , free
  default-language:    Haskell2010
  ghc-options:         -Wall -Wunused-packages

executable telomare
  hs-source-dirs:      app
  main-is:             Main.hs
  ghc-options:         -Wall
                       -Wunused-packages
                       -threaded
                       -rtsopts
                       -with-rtsopts=-N
  build-depends:       base
                     , directory
                     , filepath
                     , optparse-applicative
                     , telomare
  default-language:    Haskell2010

executable telomare-repl
  hs-source-dirs:      app
  main-is:             Repl.hs
  ghc-options:         -Wall -Wunused-packages -threaded -rtsopts -with-rtsopts=-N
  build-depends:       base
                     , containers
                     , free
                     , haskeline
                     , megaparsec
                     , mtl
                     , optparse-applicative
                     , recursion-schemes
                     , strict
                     , telomare
  default-language:    Haskell2010

executable telomare-lsp
  main-is:             LSP.hs
  hs-source-dirs:      app

  build-depends:       base
                      , containers
                      , directory
                      , filepath
                      , free
                      , lens
                      , lsp
                      , lsp-types
                      , megaparsec
                      , process
                      , stm
                      , telomare
                      , text
                      , time
                      , aeson

  default-language:    Haskell2010
  ghc-options:         -Wall
                       -threaded
                       -rtsopts
                       -with-rtsopts=-N
                       -Wunused-packages

test-suite telomare-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             Spec.hs
  other-modules:       Common
  build-depends:       QuickCheck
                     , base
                     , free
                     , hspec
                     , recursion-schemes
                     , strict
                     , telomare
  ghc-options:         -Wall -Wunused-packages -threaded -rtsopts
  default-language:    Haskell2010

test-suite telomare-parser-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             ParserTests.hs
  build-depends:       base
                     , data-fix
                     , free
                     , megaparsec
                     , strict
                     , tasty
                     , tasty-hunit
                     , telomare
  ghc-options:         -Wall -Wunused-packages -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010

test-suite telomare-resolver-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             ResolverTests.hs
  other-modules:       Common
                     , CaseTests
  build-depends:       Diff
                     , QuickCheck
                     , base
                     , data-fix
                     , free
                     , megaparsec
                     , mtl
                     , pretty-show
                     , strict
                     , tasty
                     , tasty-hunit
                     , tasty-quickcheck
                     , telomare
  ghc-options:         -Wall -Wunused-packages -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010

test-suite telomare-sizing-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             SizingTest.hs
  other-modules:       ConformanceTests
                     , RunModeTests
                     , SizingTests
  build-depends:       base
                     , bytestring
                     , containers
                     , hspec
                     , telomare
                     , strict
  ghc-options:         -Wall -Wunused-packages -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010

test-suite telomare-eal-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             EALTests.hs
  build-depends:       base
                     , containers
                     , free
                     , strict
                     , tasty
                     , tasty-hunit
                     , telomare
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010

test-suite telomare-ic-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             ICTests.hs
  build-depends:       base
                     , containers
                     , strict
                     , tasty
                     , tasty-hunit
                     , telomare
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010

test-suite telomare-udt-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             UDTTests.hs
  other-modules:       NatUDTTests
  build-depends:       base
                     , free
                     , megaparsec
                     , strict
                     , tasty
                     , tasty-hunit
                     , tasty-quickcheck
                     , telomare

  ghc-options:         -Wall -Wunused-packages -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010

source-repository head
  type:     git
  location: https://github.com/Stand-In-Language/stand-in-language
